[package]
name = "libx"
version = "0.1.0"
authors = ["schulke-214 <hello@maximilianschulke.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = "0.6.0"
